- name: Restart systemd-resolved
  ansible.builtin.systemd_service:
    name: systemd-resolved.service
    state: restarted

- name: Reload systemd-networkd config
  ansible.builtin.systemd_service:
    name: systemd-networkd.service
    state: reloaded
