- name: Add HashiCorp APT repository key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029

- name: Configure HashiCorp APT repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ hashicorp_distribution_release }} main
    filename: hashicorp
    state: present

- name: Install Apt packages
  apt:
    name:
      - consul
      - docker.io
      - systemd-resolved
      - podman
      - vim
    dpkg_options: 'force-confdef,force-confold'
    state: present

- name: Enable systemd services
  systemd_service:
    name: '{{ item }}'
    enabled: true
  with_list:
    - consul.service
    - docker.service
    - podman.service
    - systemd-networkd.service
    - systemd-resolved.service
    - systemd-timesyncd.service

- name: systemd
  copy:
    src: os/etc/systemd/system-environment-generators
    dest: /etc/systemd/
  notify:
    - Reexec systemd
  tags: systemd

- name: Update systemd-networkd config
  template:
    src: os/etc/systemd/network/80-dhcp.network.j2
    dest: /etc/systemd/network/80-dhcp.network
  notify:
    - Reload systemd-networkd config
  tags: networkd

- name: Update systemd-resolved config
  copy:
    src: os/etc/systemd/resolved.conf.d
    dest: /etc/systemd
  notify:
    - Restart systemd-resolved
  tags: resolved

- name: Setup sane editor
  alternatives:
    name: editor
    path: /usr/bin/vim.basic

- name: Update consul client config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/etc/consul.d/consul.hcl.j2
      dest: /etc/consul.d/consul.hcl
    - src: os/etc/consul.d/consul.env
      dest: /etc/consul.d/consul.env
  notify:
    - Restart consul
  tags: consul
