dc1:
  vars:
    nomad_datacenter: dc1
  hosts:
    nomad0.node.home:
    nomad1.node.home:
    nomad2.node.home:

dc2:
  vars:
    nomad_datacenter: dc2
  hosts:
    bastion.node.home:

keepalived_servers:
  hosts:
    nomad0.node.home:
      keepalived_priority: 100
    nomad1.node.home:
      keepalived_priority: 81
    nomad2.node.home:
      keepalived_priority: 82

vault_servers:
  hosts:
    nomad0.node.home:
    nomad1.node.home:
    nomad2.node.home:

consul_servers:
  hosts:
    nomad0.node.home:
    nomad1.node.home:
    nomad2.node.home:

consul_clients:
  hosts:
    bastion.node.home:
    nomad0.node.home:
    nomad1.node.home:
    nomad2.node.home:

nomad_servers:
  hosts:
    nomad0.node.home:
    nomad1.node.home:
    nomad2.node.home:

nomad_clients:
  hosts:
    bastion.node.home:
    nomad0.node.home:
    nomad1.node.home:
    nomad2.node.home:
