- name: Install Apt packages
  ansible.builtin.apt:
    name:
      - systemd-resolved
    dpkg_options: "force-confdef,force-confold"
    state: present

- name: Update systemd-networkd config
  ansible.builtin.copy:
    src: os/etc/systemd/network/80-dhcp.network
    dest: /etc/systemd/network/80-dhcp.network
    mode: "0644"
  notify:
    - Reload systemd-networkd config

- name: Update systemd-resolved config
  ansible.builtin.copy:
    src: os/etc/systemd/resolved.conf.d
    dest: /etc/systemd
    mode: "0644"
  notify:
    - Restart systemd-resolved

- name: Enable systemd services
  ansible.builtin.systemd_service:
    name: "{{ item }}"
    enabled: true
  with_list:
    - systemd-networkd.service
    - systemd-resolved.service
    - systemd-timesyncd.service
