- name: Install rtl_433 package
  apt:
    name: rtl-433
    dpkg_options: 'force-confdef,force-confold'
    state: present
  tags: rtl_433

- name: Deploy rtl_433 service
  copy:
    src: os/etc/systemd/system/rtl_433.service
    dest: /etc/systemd/system/
  tags: rtl_433

- name: Enable rtl_433 service
  systemd_service:
    name: rtl_433.service
    enabled: true
  tags: rtl_433
