- name: Reexec systemd
  systemd_service:
    daemon_reexec: true

- name: Apply sysctl
  systemd_service:
    name: systemd-sysctl.service
    state: restarted

- name: Restart systemd-resolved
  systemd_service:
    name: systemd-resolved.service
    state: restarted

- name: Reload systemd-networkd config
  systemd_service:
    name: systemd-networkd.service
    state: reloaded

- name: Update system CA certificates
  command: update-ca-certificates
  when: ansible_facts['os_family'] == 'Debian'
