- name: Install Apt packages
  ansible.builtin.apt:
    name:
      - vault
    dpkg_options: "force-confdef,force-confold"
    state: present
  notify:
    - Flag vault restart

- name: Enable vault service
  ansible.builtin.systemd_service:
    name: vault.service
    enabled: true

- name: Update vault configuration
  ansible.builtin.template:
    src: os/etc/vault.d/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
  notify:
    - Flag vault restart
