- name: Install keepalived package
  ansible.builtin.apt:
    name: keepalived
    dpkg_options: "force-confdef,force-confold"
    state: present

- name: Update keepalived config
  ansible.builtin.template:
    src: os/etc/keepalived/keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf
    mode: "0644"
  notify:
    - Restart keepalived

- name: Enable keepalived service
  ansible.builtin.systemd_service:
    name: keepalived.service
    enabled: true
