- name: Get raw udevadm info for main network interface
  command: udevadm info --value --query=property --property ID_NET_DRIVER /sys/class/net/{{ ansible_default_ipv4.interface }}
  register: udevadm_network_interface_raw_output
  check_mode: false

- name: Set default_ipv4_interface_driver fact
  set_fact:
    default_ipv4_interface_driver: "{{ udevadm_network_interface_raw_output.stdout_lines | join }}"
