- name: copy .home CA certificate
  copy:
    src: files/home-ca.pem
    dest: /usr/local/share/ca-certificates/home.crt
    owner: root
    group: root
    mode: '0644'
  tags: cacert
  notify: Update system CA certificates
  when: ansible_facts['os_family'] == 'Debian'
