- name: Add HashiCorp APT repository key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029

- name: Configure HashiCorp APT repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ hashicorp_distribution_release }} main
    filename: hashicorp
    state: present

- name: Install Apt packages
  apt:
    name:
      - consul
      - consul-cni
      - docker.io
      - nomad
      - systemd-resolved
      - podman
      - vault
    dpkg_options: 'force-confdef,force-confold'
    state: present

- name: Create clusterdata mount point
  file:
    state: directory
    path: /clusterdata
    owner: root
    group: root
    mode: '0755'
  tags: mount

- name: Add clusterdata mount point to fstab
  ansible.posix.mount:
    path: /clusterdata
    src: nasty.node.home:/volume1/clusterdata
    fstype: nfs4
    opts: nolock,x-systemd.automount,x-systemd.device-timeout=60
    dump: 0
    passno: 0
    state: present
  tags: mount

- name: systemd
  copy:
    src: os/etc/systemd/system-environment-generators
    dest: /etc/systemd/
  notify:
    - Reexec systemd
  tags: systemd

- name: Update systemd-networkd config
  copy:
    src: os/etc/systemd/network/80-dhcp.network
    dest: /etc/systemd/network/80-dhcp.network
  notify:
    - Reload systemd-networkd config
  tags: networkd

- name: Update systemd-resolved config
  copy:
    src: os/etc/systemd/resolved.conf.d
    dest: /etc/systemd
  notify:
    - Restart systemd-resolved
  tags: resolved

- name: Update consul client config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/etc/consul.d/consul.hcl.j2
      dest: /etc/consul.d/consul.hcl
    - src: os/etc/consul.d/consul.env
      dest: /etc/consul.d/consul.env
  tags: consul

- name: Update nomad config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/etc/nomad.d/base.hcl.j2
      dest: /etc/nomad.d/base.hcl
    - src: os/etc/nomad.d/client.hcl.j2
      dest: /etc/nomad.d/client.hcl
  tags: nomad

- name: Deploy vault-agent systemd service
  copy:
    src: os/etc/systemd/system/vault-agent.service
    dest: /etc/systemd/system/vault-agent.service
  tags: vault-agent

- name: Deploy vault-agent config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/etc/vault.d/agent.hcl.j2
      dest: /etc/vault.d/agent.hcl
    - src: os/etc/vault.d/agent.env.j2
      dest: /etc/vault.d/agent.env
    - src: os/etc/vault.d/agent.roleid
      dest: /etc/vault.d/agent.roleid
  tags: vault-agent

- name: Deploy vault-agent templates
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/opt/shared/tls/tls.tpl
      dest: /opt/shared/tls/tls.tpl
    - src: os/opt/consul/tls/tls.tpl
      dest: /opt/consul/tls/tls.tpl
    - src: os/opt/nomad/tls/tls.tpl
      dest: /opt/nomad/tls/tls.tpl
    - src: os/opt/vault/tls/tls.tpl
      dest: /opt/vault/tls/tls.tpl
  tags: vault-agent

- name: Enable systemd services
  systemd_service:
    name: '{{ item }}'
    enabled: true
  with_list:
    - consul.service
    - docker.service
    - podman.service
    - vault-agent.service
    - systemd-networkd.service
    - systemd-resolved.service
    - systemd-timesyncd.service

- name: sysctl
  copy:
    src: os/etc/sysctl.d
    dest: /etc
  notify:
    - Apply sysctl
  tags: sysctl

- name: Initialize capability list
  set_fact:
    hardware_capabilities: []
  tags: nomad

- name: Gather USB facts
  community.general.usb_facts:
  register: usb_facts
  tags: nomad

- name: Detect Zooz Z-Wave Controller
  set_fact:
    hardware_capabilities: "{{ hardware_capabilities + ['zwave'] }}"
  when:
    # 1a86:55d4: QinHeng Electronics 800 Z-Wave Stick
    "'1a86:55d4' in usb_devices | map(attribute='id')"
  tags: nomad

- name: Detect Intel Quicksync
  set_fact:
    hardware_capabilities: "{{ hardware_capabilities + ['quicksync'] }}"
  when:
    "'Intel(R) N100' in ansible_processor"
  tags: nomad

- name: Detect UPS
  set_fact:
    hardware_capabilities: "{{ hardware_capabilities + ['ups'] }}"
  when:
    # 051d:0003: American Power Conversion UPS
    "'051d:0003' in usb_devices | map(attribute='id')"
  tags: nomad

- name: Detect rtl433 radio
  set_fact:
    hardware_capabilities: "{{ hardware_capabilities + ['rtl433'] }}"
  when:
    # Realtek Semiconductor Corp. RTL2838 DVB-T
    "'0bda:2838' in usb_devices | map(attribute='id')"
  tags: nomad

- name: Deploy capability markers
  copy:
    content: |
      client {
        meta {
          has_{{ item }} = "true"
        }
      }
    dest: /etc/nomad.d/has_{{ item }}.hcl
    mode: '0644'
    owner: 'nomad'
    group: 'nomad'
  loop: "{{ hardware_capabilities }}"
  tags: nomad
