- name: Add HashiCorp APT repository key
  get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029

- name: Configure HashiCorp APT repository
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc] https://apt.releases.hashicorp.com {{ hashicorp_distribution_release }} main
    filename: hashicorp
    state: present

- name: Install Apt packages
  apt:
    name:
      - consul
      - consul-cni
      - docker.io
      - systemd-resolved
      - podman
    dpkg_options: 'force-confdef,force-confold'
    state: present

- name: Create clusterdata mount point
  file:
    state: directory
    path: /clusterdata
    owner: root
    group: root
    mode: '0755'
  tags: mount

- name: Add clusterdata mount point to fstab
  ansible.posix.mount:
    path: /clusterdata
    src: nasty.node.home:/volume1/clusterdata
    fstype: nfs4
    opts: nolock,x-systemd.automount,x-systemd.device-timeout=60
    dump: 0
    passno: 0
    state: present
  tags: mount

- name: Enable systemd services
  systemd_service:
    name: '{{ item }}'
    enabled: true
  with_list:
    - consul.service
    - docker.service
    - podman.service
    - systemd-networkd.service
    - systemd-resolved.service
    - systemd-timesyncd.service

- name: systemd
  copy:
    src: os/etc/systemd/system-environment-generators
    dest: /etc/systemd/
  notify:
    - Reexec systemd
  tags: systemd

- name: Update systemd-networkd config
  copy:
    src: os/etc/systemd/network/80-dhcp.network
    dest: /etc/systemd/network/80-dhcp.network
  notify:
    - Reload systemd-networkd config
  tags: networkd

- name: Update systemd-resolved config
  copy:
    src: os/etc/systemd/resolved.conf.d
    dest: /etc/systemd
  notify:
    - Restart systemd-resolved
  tags: resolved

- name: Update consul client config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/etc/consul.d/consul.hcl.j2
      dest: /etc/consul.d/consul.hcl
    - src: os/etc/consul.d/consul.env
      dest: /etc/consul.d/consul.env
  notify:
    - Restart consul
  tags: consul

- name: Update nomad config
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - src: os/etc/nomad.d/base.hcl.j2
      dest: /etc/nomad.d/base.hcl
    - src: os/etc/nomad.d/client.hcl
      dest: /etc/nomad.d/client.hcl
  notify:
    - Restart nomad
  tags: nomad

- name: sysctl
  copy:
    src: os/etc/sysctl.d
    dest: /etc
  notify:
    - Apply sysctl
  tags: sysctl

- name: Gather USB facts
  community.general.usb_facts:
  register: usb_facts
  tags:
    - nomad
    - rtl_433

- name: Import rtl_433 tasks
  import_tasks:
    file: rtl_433.yml
  when:
    # Realtek Semiconductor Corp. RTL2838 DVB-T
    "'0bda:2838' in usb_devices | map(attribute='id')"

- name: Deploy Z-Wave capability marker
  copy:
    content: |
      client {
        meta {
          has_zwave = "true"
        }
      }
    dest: /etc/nomad.d/has_zwave.hcl
    mode: '0644'
    owner: 'nomad'
    group: 'nomad'
  when:
    # 1a86:55d4: QinHeng Electronics 800 Z-Wave Stick
    "'1a86:55d4' in usb_devices | map(attribute='id')"
  tags: nomad

- name: Deploy Quicksync capability marker
  copy:
    content: |
      client {
        meta {
          has_quicksync = "true"
        }
      }
    dest: /etc/nomad.d/has_quicksync.hcl
    mode: '0644'
    owner: 'nomad'
    group: 'nomad'
  when:
    "'Intel(R) N100' in ansible_processor"
  tags: nomad

- name: Deploy UPS capability marker
  copy:
    content: |
      client {
        meta {
          has_ups = "true"
        }
      }
    dest: /etc/nomad.d/has_ups.hcl
    mode: '0644'
    owner: 'nomad'
    group: 'nomad'
  when:
    # 051d:0003: American Power Conversion UPS
    "'051d:0003' in usb_devices | map(attribute='id')"
  tags: nomad
