- name: Include nomad sub-tasks
  import_tasks:
    file: nomad.yml

- name: Include vault sub-tasks
  import_tasks:
    file: vault.yml

- name: Include keepalived sub-tasks
  import_tasks:
    file: keepalived.yml

