- name: Gather USB facts
  community.general.usb_facts:
  register: usb_facts
  tags:
    - nomad
    - rtl_433

- name: Include nomad sub-tasks
  import_tasks:
    file: nomad.yml

- name: Include vault sub-tasks
  import_tasks:
    file: vault.yml

- name: Include keepalived sub-tasks
  import_tasks:
    file: keepalived.yml

- name: Import rtl_433 tasks
  import_tasks:
    file: rtl_433.yml
  when:
    # Realtek Semiconductor Corp. RTL2838 DVB-T
    "'0bda:2838' in usb_devices | map(attribute='id')"

