- name: Enable vault service
  systemd_service:
    name: vault.service
    enabled: true
  tags: vault

- name: Update vault configuration
  template:
    src: os/etc/vault.d/vault.hcl.j2
    dest: /etc/vault.d/vault.hcl
  tags: vault
