- name: Enable vault service
  systemd_service:
    name: vault.service
    enabled: true
  tags: vault

- name: Update vault configuration
  copy:
    src: os/etc/vault.d/vault.hcl
    dest: /etc/vault.d/vault.hcl
  notify:
    - Restart vault
  tags: vault
